apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
commonLabels:
  app.kubernetes.io/managed-by: kustomize
resources:
  - deployments.yaml
  - services.yaml
  - servicemonitors.yaml
  - localstack.yaml
  - postgres.yaml
  - kafka-external-service.yaml
  - frontend-deployment.yaml
  - frontend-ingress.yaml
  - frontend-servicemonitor.yaml
  - hpas.yaml
  - flink-job.yaml
  - load-testing.yaml
  - grafana-dashboards.yaml
  - logging-stack.yaml

