apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
commonLabels:
  app.kubernetes.io/managed-by: kustomize
resources:
  - deployments.yaml
  - services.yaml
  - servicemonitors.yaml
  - localstack.yaml
  - postgres.yaml
  - kafka.yaml
  # frontend k8s manifests are currently empty in the repo; include them when populated

