apiVersion: v1
kind: Secret
metadata:
  name: cart-secrets
type: Opaque
data:
  # Base64 encoded values
  # Replace with: echo -n 'your-value' | base64
  aws_access_key_id: QVBJX0tFWV9JRCBISVI=
  aws_secret_access_key: QVBJX1NFQ1JFVF9LRVkgSElSRQ==

